# Generated by Django 6.0.3 on 2026-03-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name_client',
        ),
    ]
