# Generated by Django 6.0.3 on 2026-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='enderecoclient',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
    ]
