# Generated by Django 6.0.3 on 2026-03-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dispositivo', models.CharField(choices=[('NT', 'Notebook'), ('DK', 'Desktop')], default='DK', max_length=2)),
                ('nome_meu_dispositivo', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(choices=[('LI', 'Limpeza'), ('MN', 'Manuntenção'), ('FO', 'Formatcação')], default='FO', max_length=2)),
                ('data_servico', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dispositivo')),
            ],
        ),
    ]
